name: 'typedocusaurus'

on:
  workflow_dispatch:
    inputs:
      sourcePath:
        required: true
      targetPath:
        required: true
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test!"
