name: test action

on:
  pull_request:
  push:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout tauri-docs
        uses: actions/checkout@v2
        with:
          repository: tauri-apps/tauri-docs
          path: tauri-docs
      - name: checkout tauri
        uses: actions/checkout@v2
        with:
          repository: tauri-apps/tauri
          path: tauri
      - uses: actions/setup-node@v2
        with:
          path: ./tauri/tooling/api/
      - name: run typedocusaurus
        uses: ./
        with:
          originPath: ./tauri/tooling/api/
          targetPath: ./tauri-docs/docs/api/js/
          docusaurusPath: ./tauri-docs/
